### ISSUE TITLE
Getting a list index out of range error

### ISSUE THREAD

**Issue by genidma** [edubey/text-summarizer#2]
Greetings, 

The last line is generating errors for me. I think it has to do with how the text is formatted in the textfile that I am using. 

Here is the error message that I am getting: 

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/<redacted>/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
More Is Different

Indexes of top ranked_sentence order are  []
Traceback (most recent call last):
  File "text-summarizer.py", line 87, in <module>
    generate_summary( "moreisdifferent.txt", 2)
  File "text-summarizer.py", line 81, in generate_summary
    summarize_text.append(" ".join(ranked_sentence[i][1]))
IndexError: list index out of range

**Comment by HrithikMittal** [comment]
I also get the same error

**Comment by HrithikMittal** [comment]
Hey I think you are missing something @genidma and check out the code from here
https://gist.github.com/edubey/cc41dbdec508a051675daf8e8bba62c5#file-text-summarization-py-L9

**Comment by HrithikMittal** [comment]
Hey for that i think we can just require the text and it would be easy if it's a Wikipedia as there would be no javascript. I think we can scrap down the data and then use it.
Give me some time i will share the link of repo used for scrapping.

**Comment by genidma** [comment]
Hi Adhi

Are we meeting next week?

I am not logged on LinkedIn at the moment.

**Comment by HrithikMittal** [comment]
ya sure

**Comment by EuvolaGG** [comment]
hello...am very new to this and am trying to get different files  to the summarizer but am unable to see where to adjust in the script to get the file names as user input.Sorry for the poor english.

**Comment by ironhackz** [comment]
> Hey I think you are missing something @genidma and check out the code from here
> https://gist.github.com/edubey/cc41dbdec508a051675daf8e8bba62c5#file-text-summarization-py-L9

Sorry but still didn't get the solution to this error.....do u mind elaborating on the solution

**Comment by deanlongio** [comment]
I have the same issue too
